worker: node bot.js
worker: node bot2.js
worker: node bot3.js
worker: node bot4.js
worker: node bot5.js
worker: node bot6.js
worker: node bot7.js
worker: node bot8.js
worker: node bot9.js
worker: node bot10.js
worker: node bot11.js
worker: node bot12.js
worker: node bot13.js
worker: node bot14.js
worker: node bot15.js
worker: node bot16.js
worker: node bot17.js
worker: node bot18.js
worker: node bot19.js
worker: node bot20.js
worker: node bot21.js
worker: node bot22.js
worker: node bot23.js
worker: node bot24.js
worker: node bot25.js
worker: node bot26.js
worker: node bot27.js
worker: node bot28.js
worker: node bot29.js
worker: node bot30.js
worker: node bot31.js
worker: node bot32.js
worker: node bot33.js
worker: node bot34.js
worker: node bot35.js
worker: node bot36.js
worker: node bot37.js
worker: node bot38.js
worker: node bot39.js
worker: node bot40.js
